version: "3.5"

services:
  ts-starter-service:
    image: ts-starter:1.0.0
    build: ./
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: always
    ports:
      - "5000:5000"
    env_file: "./docker_env/local/docker.local.env"
    depends_on: 
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - "/data/db:/data/db"
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: kramaDb@123
    ports:
      - "27017:27017"