/**
 * @interface
 * @description This defines the data generated by token generator.
 * @exports Token
 */
export default interface Token{
  token: string;
  secret: string;
  expiryTimeInMinutes: string;
}